VERILOG_SOURCES     = $(PWD)/../../rtl/encaps_top.v \
                      $(PWD)/../../rtl/encaps_ctrl.v \
                      $(PWD)/../../rtl/kyber_top.v \
                      $(PWD)/../../rtl/poly_ram.v \
                      $(PWD)/../../rtl/ntt_engine.v \
                      $(PWD)/../../rtl/ntt_butterfly.v \
                      $(PWD)/../../rtl/intt_butterfly.v \
                      $(PWD)/../../rtl/ntt_rom.v \
                      $(PWD)/../../rtl/barrett_reduce.v \
                      $(PWD)/../../rtl/cond_sub_q.v \
                      $(PWD)/../../rtl/cond_add_q.v \
                      $(PWD)/../../rtl/mod_add.v \
                      $(PWD)/../../rtl/mod_sub.v \
                      $(PWD)/../../rtl/poly_basemul.v \
                      $(PWD)/../../rtl/basemul_unit.v \
                      $(PWD)/../../rtl/cbd_sampler.v \
                      $(PWD)/../../rtl/compress.v \
                      $(PWD)/../../rtl/decompress.v
TOPLEVEL            = encaps_top
COCOTB_TEST_MODULES = test_acvp_encaps

include ../common.mk
