VERILOG_SOURCES     = $(PWD)/../../rtl/ntt_butterfly.v \
                      $(PWD)/../../rtl/barrett_reduce.v \
                      $(PWD)/../../rtl/mod_add.v \
                      $(PWD)/../../rtl/mod_sub.v \
                      $(PWD)/../../rtl/cond_sub_q.v \
                      $(PWD)/../../rtl/cond_add_q.v
TOPLEVEL            = ntt_butterfly
COCOTB_TEST_MODULES = test_ntt_butterfly

include ../common.mk
