VERILOG_SOURCES     = $(PWD)/../../rtl/poly_basemul.v \
                      $(PWD)/../../rtl/basemul_unit.v \
                      $(PWD)/../../rtl/poly_ram.v \
                      $(PWD)/../../rtl/ntt_rom.v \
                      $(PWD)/../../rtl/barrett_reduce.v \
                      $(PWD)/../../rtl/cond_sub_q.v
TOPLEVEL            = poly_basemul
COCOTB_TEST_MODULES = test_poly_basemul

include ../common.mk
