VERILOG_SOURCES     = $(PWD)/compress_tb_wrapper.v \
                      $(PWD)/../../rtl/compress.v
TOPLEVEL            = compress_tb_wrapper
COCOTB_TEST_MODULES = test_compress

include ../common.mk
