VERILOG_SOURCES     = $(PWD)/../../rtl/intt_butterfly.v \
                      $(PWD)/../../rtl/barrett_reduce.v \
                      $(PWD)/../../rtl/mod_add.v \
                      $(PWD)/../../rtl/mod_sub.v \
                      $(PWD)/../../rtl/cond_sub_q.v \
                      $(PWD)/../../rtl/cond_add_q.v
TOPLEVEL            = intt_butterfly
COCOTB_TEST_MODULES = test_intt_butterfly

include ../common.mk
