VERILOG_SOURCES     = $(PWD)/decompress_tb_wrapper.v \
                      $(PWD)/../../rtl/decompress.v
TOPLEVEL            = decompress_tb_wrapper
COCOTB_TEST_MODULES = test_decompress

include ../common.mk
