VERILOG_SOURCES     = $(PWD)/../../rtl/ntt_engine.v \
                      $(PWD)/../../rtl/poly_ram.v \
                      $(PWD)/../../rtl/ntt_rom.v \
                      $(PWD)/../../rtl/ntt_butterfly.v \
                      $(PWD)/../../rtl/intt_butterfly.v \
                      $(PWD)/../../rtl/barrett_reduce.v \
                      $(PWD)/../../rtl/mod_add.v \
                      $(PWD)/../../rtl/mod_sub.v \
                      $(PWD)/../../rtl/cond_sub_q.v \
                      $(PWD)/../../rtl/cond_add_q.v
TOPLEVEL            = ntt_engine
COCOTB_TEST_MODULES = test_ntt_engine

include ../common.mk
