VERILOG_SOURCES     = $(PWD)/../../rtl/basemul_unit.v \
                      $(PWD)/../../rtl/barrett_reduce.v \
                      $(PWD)/../../rtl/cond_sub_q.v
TOPLEVEL            = basemul_unit
COCOTB_TEST_MODULES = test_basemul_unit

include ../common.mk
