VERILOG_SOURCES     = $(PWD)/../../rtl/cbd_sampler.v \
                      $(PWD)/../../rtl/poly_ram.v
TOPLEVEL            = cbd_sampler
COCOTB_TEST_MODULES = test_cbd_sampler

include ../common.mk
