VERILOG_SOURCES     = $(PWD)/../../rtl/poly_addsub.v \
                      $(PWD)/../../rtl/poly_ram.v \
                      $(PWD)/../../rtl/mod_add.v \
                      $(PWD)/../../rtl/mod_sub.v \
                      $(PWD)/../../rtl/cond_sub_q.v \
                      $(PWD)/../../rtl/cond_add_q.v
TOPLEVEL            = poly_addsub
COCOTB_TEST_MODULES = test_poly_addsub

include ../common.mk
