VERILOG_SOURCES     = $(PWD)/../../rtl/keccak_sponge.v \
                      $(PWD)/../../rtl/keccak_round.v \
                      $(PWD)/../../rtl/keccak_rc.v
TOPLEVEL            = keccak_sponge
COCOTB_TEST_MODULES = test_keccak_sponge

include ../common.mk
